-- Quiz 4 --

-- Given the candy database tables, list 3 different order all the tables in the database can be legally dropped --
-- 1 --
DROP TABLE IF EXISTS candy_purchase;
DROP TABLE IF EXISTS candy_customer;
DROP TABLE IF EXISTS candy_cust_type;
DROP TABLE IF EXISTS candy_product;

-- 2 --
DROP TABLE IF EXISTS candy_purchase;
DROP TABLE IF EXISTS candy_customer;
DROP TABLE IF EXISTS candy_product;
DROP TABLE IF EXISTS candy_cust_type;

-- 3 --
DROP TABLE IF EXISTS candy_purchase;
DROP TABLE IF EXISTS candy_product;
DROP TABLE IF EXISTS candy_customer;
DROP TABLE IF EXISTS candy_cust_type;

-- Q2 --

CREATE TABLE PUBLISHER
(PUBLISHER_CODE CHAR(3),
PUSBISHER_NAME CHAR(25),
CITY CHAR(20),
CONSTRAINT PUBLISHER_CODE_PK PRIMARY KEY (PUBLISHER_CODE));

CREATE TABLE AUTHOR
(AUTHOR_ID DECIMAL(2, 0),
AUTHOR_LAST CHAR(12),
AUTHOR_FIRST CHAR(10),
CONSTRAINT AUTHOR_ID_PK PRIMARY KEY (AUTHOR_ID));

CREATE TABLE BOOK
(BOOK_CODE CHAR(4),
TITLE CHAR(40),
PUBLISHER_CODE CHAR(3),
PRICE DECIMAL(4,2),
PAPERBACK CHAR(1),
CONSTRAINT BOOK_CODE_PK PRIMARY KEY (BOOK_CODE),
CONSTRAINT PUBLISHER_CODE_FK FOREIGN KEY (PUBLISHER_CODE) REFERENCES PUBLISHER(PUBLISHER_CODE));

CREATE TABLE WROTE
(BOOK_CODE CHAR(4),
AUTHOR_ID DECIMAL(2,0),
CONSTRAINT BOOK_CODE_FK FOREIGN KEY (BOOK_CODE) REFERENCES BOOK(BOOK_CODE),
CONSTRAINT AUTHOR_ID_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID),
CONSTRAINT BOOK_CODE_AUTH_ID PRIMARY KEY (BOOK_CODE, AUTHOR_ID));


DROP TABLE IF EXISTS WROTE;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS PUBLISHER;



