-- Lab 4 Insert --

INSERT INTO MUSIC_ARTIST
VALUES
(NULL,'Nirvana','Seattle, WA','Rock');
INSERT INTO MUSIC_ARTIST
VALUES
(NULL,'Miles Davis','Aton, IL','Jazz');
INSERT INTO MUSIC_ARTIST
VALUES
(NULL,'Micheal Jackson','Gary, IN','Pop');
INSERT INTO MUSIC_ARTIST
VALUES
(NULL,"Lil' Wayne",'New Orleans, LA','Hip Hop');
INSERT INTO MUSIC_ARTIST
VALUES
(NULL,'Willie Nelson','Abbott, TX','Country');


INSERT INTO MUSIC_LABEL
VALUES
(NULL,'DGC Records');
INSERT INTO MUSIC_LABEL
VALUES
(NULL,'Columbia');
INSERT INTO MUSIC_LABEL
VALUES
(NULL,'Epic Records');
INSERT INTO MUSIC_LABEL
VALUES
(NULL,'Cash Money');

INSERT INTO MUSIC_FORMAT
VALUES
('V', 'Vinyl');
INSERT INTO MUSIC_FORMAT
VALUES
('T', 'Cassette Tape');
INSERT INTO MUSIC_FORMAT
VALUES
('C', 'Compact Disk');
INSERT INTO MUSIC_FORMAT
VALUES
('D', 'Digital');


INSERT INTO MUSIC_ALBUM
VALUES
(NULL,'Nevermind', 
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = 'Nirvana') ,
'1991-09-23','30000000',
(SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_NAME = 'Compact Disk') , -- I can use placeholder single Char--
 (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'DGC Records'));
INSERT INTO MUSIC_ALBUM
VALUES
(NULL,'In Utero',
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = 'Nirvana'),
'1993-09-21','15000000',
 (SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_NAME = 'Compact Disk'),
 (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'DGC Records'));
INSERT INTO MUSIC_ALBUM
VALUES
(NULL,'Kind of Blue',
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = 'Miles Davis'),
'1959-08-17','4000000',
(SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_NAME = 'Vinyl'),
(SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'Columbia'));
INSERT INTO MUSIC_ALBUM
VALUES
(NULL,'Thriller',
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = 'Micheal Jackson'),
'1982-11-30','65000000',
 (SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_NAME = 'Cassette Tape'),
 (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'Epic Records'));
INSERT INTO MUSIC_ALBUM
VALUES
(NULL,'Bad',
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = 'Micheal Jackson'),
'1987-09-01','45000000',
 (SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_NAME = 'Cassette Tape'),
 (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'Epic Records'));
INSERT INTO MUSIC_ALBUM
VALUES
(NULL,'The Carter III',
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = "Lil' Wayne"),
'2008-06-09','3800000',
 (SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_NAME = 'Digital'),
 (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'Cash Money'));
INSERT INTO MUSIC_ALBUM
VALUES
(NULL,'Red Headed Stranger',
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = 'Willie Nelson'),
'1975-05-01','2000000',
 (SELECT FORMAT_ID FROM MUSIC_FORMAT WHERE FORMAT_NAME = 'Vinyl'),
 (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'Columbia'));



SELECT * FROM MUSIC_ARTIST;
SELECT * FROM MUSIC_LABEL;
SELECT * FROM MUSIC_ALBUM;
SELECT * FROM MUSIC_FORMAT;
