-- Matt Krzewinski and Sean Wendlandt --

-- DROPPING TABLES -- 
DROP TABLE IF EXISTS VG_INFO;
DROP TABLE IF EXISTS VG_VIDEO_GAME;
DROP TABLE IF EXISTS VG_PLATFORM;
DROP TABLE IF EXISTS VG_GENRE;
DROP TABLE IF EXISTS VG_PUBLISHER;

-- CREATING TABLES -- 

-- PUBLISHER TABLE --
CREATE TABLE VG_PUBLISHER
(
	PUBLISHER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PUBLISHER_NAME VARCHAR(38)
);


-- GENRE TABLE --
CREATE TABLE VG_GENRE
(
	GENRE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    GENRE_NAME VARCHAR(12)
);


-- PLATFORM TABLE -- 
CREATE TABLE VG_PLATFORM
(
	PLATFORM_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PLATFORM_NAME VARCHAR(4)
);


-- VIDEO GAME TABLE --
CREATE TABLE VG_VIDEO_GAME
(
	GAME_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    VG_NAME VARCHAR(132),
    GENRE_ID BIGINT,
    CONSTRAINT GENRE_ID_FK FOREIGN KEY (GENRE_ID) REFERENCES VG_GENRE(GENRE_ID)
);


-- INFO (LINKING) TABLE -- 
CREATE TABLE VG_INFO
(
	RELEASE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    YEAR DATE,
    NA_SALES DOUBLE,
    EU_SALES DOUBLE,
    JP_SALES DOUBLE,
    OTHER_SALES DOUBLE,
    GAME_ID BIGINT,
    PUBLISHER_ID BIGINT,
    PLATFORM_ID BIGINT,
    CONSTRAINT GAME_ID_FK FOREIGN KEY (GAME_ID) REFERENCES VG_VIDEO_GAME(GAME_ID),
    CONSTRAINT PUBLISHER_ID_FK FOREIGN KEY (PUBLISHER_ID) REFERENCES VG_PUBLISHER(PUBLISHER_ID),
    CONSTRAINT PLATFORM_ID_FK FOREIGN KEY (PLATFORM_ID) REFERENCES VG_PLATFORM(PLATFORM_ID)
);

-- INSERTING DATA --

-- PUBLISHER TABLE --
INSERT INTO VG_PUBLISHER (PUBLISHER_NAME)
(SELECT DISTINCT PUBLISHER FROM vg_csv WHERE PUBLISHER != 'N/A');


-- GENRE TABLE --
INSERT INTO VG_GENRE (GENRE_NAME)
(SELECT DISTINCT GENRE FROM vg_csv);


-- PLATFORM TABLE --
INSERT INTO VG_PLATFORM (PLATFORM_NAME)
(SELECT DISTINCT PLATFORM FROM vg_csv);


-- VIDEO GAME TABLE -- 
INSERT INTO VG_VIDEO_GAME (VG_NAME, GENRE_ID)
(SELECT DISTINCT NAME, (SELECT genre_id FROM vg_genre WHERE genre_name = vg_csv.genre)
FROM vg_csv);


-- INFO (LINKING) TABLE -- 
INSERT INTO VG_INFO (YEAR, NA_SALES, EU_SALES, JP_SALES, OTHER_SALES, GAME_ID, PUBLISHER_ID, PLATFORM_ID)
(SELECT
CASE WHEN year = 'N/A' THEN NULL ELSE CONCAT(year, '-01-01') END, na_sales, eu_sales, jp_sales, other_sales, 
(SELECT game_id FROM vg_video_game where vg_name = vg_csv.name), 
(SELECT publisher_id FROM vg_publisher where publisher_name = vg_csv.publisher),
(SELECT platform_id FROM vg_platform where platform_name = vg_csv.platform)
FROM vg_csv);


-- SELECT STATEMENTS TO SEE DATA IN TABLES --
SELECT * 
FROM VG_PUBLISHER;

SELECT * 
FROM VG_GENRE;

SELECT *
FROM VG_PLATFORM;

SELECT *
FROM VG_VIDEO_GAME;

SELECT * 
FROM VG_INFO;
